{
  "formatVersion": "1.1",
  "component": {
    "group": "com.astropay",
    "module": "connect-native-kyc",
    "version": "1.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "nativeKycReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:kyc": "nativeKyc",
        "kyc": "nativeKyc",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "connect-native-kyc-1.0.16.aar",
          "url": "connect-native-kyc-1.0.16.aar",
          "size": 358627,
          "sha512": "870888d6d8a8592d5ad83446964c38276f4cf4c69f706c9729c585094128dfa46bbd36e5627c280122fb259dfe3b8f1db3d41d54342244346e48388d569d5870",
          "sha256": "ede33b279b167726f93f78e39243f89e16f95a1443c35e40ab5192a3e7e639c6",
          "sha1": "ad5dfdce2e367d7e27cb65f6be8fe6e54dc0ad73",
          "md5": "1e926c301fc2dfd13af66ba09c591d8f"
        }
      ]
    },
    {
      "name": "nativeKycReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:kyc": "nativeKyc",
        "kyc": "nativeKyc",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.caf.sdk",
          "module": "caf-sdk-bom",
          "version": {
            "requires": "7.14.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.caf.sdk",
          "module": "caffaceliveness"
        },
        {
          "group": "io.caf.sdk",
          "module": "caffaceliveness-ui"
        },
        {
          "group": "io.caf.sdk",
          "module": "caffaceliveness-providers-iproov-lite"
        },
        {
          "group": "io.caf.sdk",
          "module": "caffaceliveness-providers-facetec"
        },
        {
          "group": "io.caf.sdk",
          "module": "document-detector-ui",
          "excludes": [
            {
              "group": "org.tensorflow",
              "module": "tensorflow-lite-support-api"
            },
            {
              "group": "org.tensorflow",
              "module": "tensorflow-lite"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "connect-native-kyc-1.0.16.aar",
          "url": "connect-native-kyc-1.0.16.aar",
          "size": 358627,
          "sha512": "870888d6d8a8592d5ad83446964c38276f4cf4c69f706c9729c585094128dfa46bbd36e5627c280122fb259dfe3b8f1db3d41d54342244346e48388d569d5870",
          "sha256": "ede33b279b167726f93f78e39243f89e16f95a1443c35e40ab5192a3e7e639c6",
          "sha1": "ad5dfdce2e367d7e27cb65f6be8fe6e54dc0ad73",
          "md5": "1e926c301fc2dfd13af66ba09c591d8f"
        }
      ]
    },
    {
      "name": "nativeKycReleaseSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:kyc": "nativeKyc",
        "kyc": "nativeKyc",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "connect-native-kyc-1.0.16-sources.jar",
          "url": "connect-native-kyc-1.0.16-sources.jar",
          "size": 186167,
          "sha512": "f3a6684a38138753f34882681fb1c0d762c4e327e3b0bcd4261fa7c438522926cad1dbced02f9560646af1a42fde03e47da4939e3c326806a336ace3fc12b8de",
          "sha256": "cacf5acb27607c743bffe221daff66e6f5b3d868c8c4f45a0d0c57de7d494363",
          "sha1": "8fb2603280cce39400d70e333e02b816a70c482c",
          "md5": "652ff6af69bcba4343e6f91e20de5b27"
        }
      ]
    }
  ]
}
