{
  "formatVersion": "1.1",
  "component": {
    "group": "com.astropay",
    "module": "connect",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "coreReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:kyc": "core",
        "kyc": "core",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "connect-1.0.17.aar",
          "url": "connect-1.0.17.aar",
          "size": 376334,
          "sha512": "49fdfe8d8b70a2f1e97fe92c05ae329bd233bf9b88b03083c9c9d19b6003e30c56c5ee3fbd8106d6443509422d09f9cad54a9a90922ed522a97ff870e690564f",
          "sha256": "0b450d4ab4311178ee19b970456332ad5b19c06df696805176c5ff4aed6ff8af",
          "sha1": "599d8428bbf54ba1722e543ce870a79341a80a8c",
          "md5": "67c05e8ba3f05531ff4cb8bc8da1d803"
        }
      ]
    },
    {
      "name": "coreReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:kyc": "core",
        "kyc": "core",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "connect-1.0.17.aar",
          "url": "connect-1.0.17.aar",
          "size": 376334,
          "sha512": "49fdfe8d8b70a2f1e97fe92c05ae329bd233bf9b88b03083c9c9d19b6003e30c56c5ee3fbd8106d6443509422d09f9cad54a9a90922ed522a97ff870e690564f",
          "sha256": "0b450d4ab4311178ee19b970456332ad5b19c06df696805176c5ff4aed6ff8af",
          "sha1": "599d8428bbf54ba1722e543ce870a79341a80a8c",
          "md5": "67c05e8ba3f05531ff4cb8bc8da1d803"
        }
      ]
    },
    {
      "name": "coreReleaseSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:kyc": "core",
        "kyc": "core",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "connect-1.0.17-sources.jar",
          "url": "connect-1.0.17-sources.jar",
          "size": 183191,
          "sha512": "b58f3840f8f97ac1b45bc1fe560eee291f59546e57bede798ab450bcb0f5579bb2bb27c39b8451b348444b24b6362dcc4943bb1985ad32bcffebc1ebc920eafc",
          "sha256": "fe990cfd36ce992e07ce91700f772197d13973df6512f71029a89beffc9126b5",
          "sha1": "ae8b5fb475f33ccd1ae1cdf959eb094ce22957f5",
          "md5": "7c83a5df071b6ea2ee9e80a6ae982758"
        }
      ]
    }
  ]
}
