{
  "formatVersion": "1.1",
  "component": {
    "group": "com.astropay",
    "module": "connect-native-kyc",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "nativeKycReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:kyc": "nativeKyc",
        "kyc": "nativeKyc",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "connect-native-kyc-1.0.17.aar",
          "url": "connect-native-kyc-1.0.17.aar",
          "size": 388055,
          "sha512": "07ea73f6b5995e11716d51c1267b6a07e59934cb88b55cd739fcf4690ebf68331cfda0d02c2f34c88652ec48207651ff382b921b9f5733ad6979c80935262140",
          "sha256": "0ffbba61bc3b1ab984817d88930e4ac25243f58830045b01dc822236d2a0f980",
          "sha1": "4716ef00ee71263ab14749bb48e7b185939e537c",
          "md5": "fd0b03ec688f9d5fe6211a76f0285385"
        }
      ]
    },
    {
      "name": "nativeKycReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:kyc": "nativeKyc",
        "kyc": "nativeKyc",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.caf.sdk",
          "module": "caf-sdk-bom",
          "version": {
            "requires": "7.14.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.caf.sdk",
          "module": "caffaceliveness"
        },
        {
          "group": "io.caf.sdk",
          "module": "caffaceliveness-ui"
        },
        {
          "group": "io.caf.sdk",
          "module": "caffaceliveness-providers-iproov-lite"
        },
        {
          "group": "io.caf.sdk",
          "module": "caffaceliveness-providers-facetec"
        },
        {
          "group": "io.caf.sdk",
          "module": "document-detector-ui",
          "excludes": [
            {
              "group": "org.tensorflow",
              "module": "tensorflow-lite-support-api"
            },
            {
              "group": "org.tensorflow",
              "module": "tensorflow-lite"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "connect-native-kyc-1.0.17.aar",
          "url": "connect-native-kyc-1.0.17.aar",
          "size": 388055,
          "sha512": "07ea73f6b5995e11716d51c1267b6a07e59934cb88b55cd739fcf4690ebf68331cfda0d02c2f34c88652ec48207651ff382b921b9f5733ad6979c80935262140",
          "sha256": "0ffbba61bc3b1ab984817d88930e4ac25243f58830045b01dc822236d2a0f980",
          "sha1": "4716ef00ee71263ab14749bb48e7b185939e537c",
          "md5": "fd0b03ec688f9d5fe6211a76f0285385"
        }
      ]
    },
    {
      "name": "nativeKycReleaseSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:kyc": "nativeKyc",
        "kyc": "nativeKyc",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "connect-native-kyc-1.0.17-sources.jar",
          "url": "connect-native-kyc-1.0.17-sources.jar",
          "size": 198903,
          "sha512": "05e54cbc7895b926576aca8c361dffc893eb7a46613547dcc4b02503c48ce5aedac8b47ee5cda26dd05d407ae636ffc2a6e73557ffb044aff532c389804289f5",
          "sha256": "7c6b4852f7db9296bc6e877d83580b5f034103aa8ff237a4951f3da5e30cc208",
          "sha1": "a4942e217ecb224cab8a4dd46c26f9b1b26db182",
          "md5": "b566d4672ffde66217017d233904d8ce"
        }
      ]
    }
  ]
}
