{
  "formatVersion": "1.1",
  "component": {
    "group": "com.astropay",
    "module": "connect",
    "version": "1.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "connect-1.0.12.aar",
          "url": "connect-1.0.12.aar",
          "size": 189289,
          "sha512": "7df4aa7603cc4ec5a4b3da0bca2e5adf9b6eea51bfbbb5f62b654b4015bd46f048b3e234ab6160ce3c8ab27a64f6907125a028f90ec196ea020c30f18758d004",
          "sha256": "dc6828a908b2d3895745c36b85a7a891bf9234375a969eb1a36a3d5b1a3609f7",
          "sha1": "3267ff03f5ef388e7ec58d5398af9fe3822e8df8",
          "md5": "bb2dcca0aeaef78b8fb8849991e5ef0e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "connect-1.0.12.aar",
          "url": "connect-1.0.12.aar",
          "size": 189289,
          "sha512": "7df4aa7603cc4ec5a4b3da0bca2e5adf9b6eea51bfbbb5f62b654b4015bd46f048b3e234ab6160ce3c8ab27a64f6907125a028f90ec196ea020c30f18758d004",
          "sha256": "dc6828a908b2d3895745c36b85a7a891bf9234375a969eb1a36a3d5b1a3609f7",
          "sha1": "3267ff03f5ef388e7ec58d5398af9fe3822e8df8",
          "md5": "bb2dcca0aeaef78b8fb8849991e5ef0e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "connect-1.0.12-sources.jar",
          "url": "connect-1.0.12-sources.jar",
          "size": 89739,
          "sha512": "7a3d070c42ba4ac43b3185dc2825c831a8a5f9195ef260d0f4063657d1665603054f5a2d67ba2c05f792dca0bc7370e5f7acb0aad87c540b08bb503139810b38",
          "sha256": "ca1593277c5d2ce91890fbaa0118789350c4d7eef0110e3d293c5dfbcd6f336f",
          "sha1": "d3f3c7aef00a9a03e89480701c858cad00ff2b85",
          "md5": "1374de8d480ec0a644500a8ff47d03b3"
        }
      ]
    }
  ]
}
