{
  "formatVersion": "1.1",
  "component": {
    "group": "com.astropay",
    "module": "connect",
    "version": "1.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "connect-1.0.11.aar",
          "url": "connect-1.0.11.aar",
          "size": 158033,
          "sha512": "b0e75d406d741200ca8be7fe4855165539f53c2f56fbbb03eb90baf67c10382ea43ccd22864231c1db1e7cf11d3914b76b72d7448cdabf52b42ec7160f5768e5",
          "sha256": "8cd5a02a406b53e680d242b8849bf71252755faf4571eb6ffb3c524379dc122d",
          "sha1": "e76b6f42f77fbb8c9b82b7c68837307b40a36f7b",
          "md5": "00a5bcb73417d584d514c5a2d1338fd5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "connect-1.0.11.aar",
          "url": "connect-1.0.11.aar",
          "size": 158033,
          "sha512": "b0e75d406d741200ca8be7fe4855165539f53c2f56fbbb03eb90baf67c10382ea43ccd22864231c1db1e7cf11d3914b76b72d7448cdabf52b42ec7160f5768e5",
          "sha256": "8cd5a02a406b53e680d242b8849bf71252755faf4571eb6ffb3c524379dc122d",
          "sha1": "e76b6f42f77fbb8c9b82b7c68837307b40a36f7b",
          "md5": "00a5bcb73417d584d514c5a2d1338fd5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "connect-1.0.11-sources.jar",
          "url": "connect-1.0.11-sources.jar",
          "size": 70565,
          "sha512": "a4169c6ab2ec584853da20d89ee54667cd140499b7974949d3c5f5eb347fd108f64db625941d3351bdd981325b585ec03d4c881f41450941fb2aa2fd939202b0",
          "sha256": "2e56cdedb77a128969fb75463bb4af71929470afec87a445d3f4310f047020f6",
          "sha1": "0aa22e85d5adb1e2c33e32a6b7a0703db3073bfa",
          "md5": "9c0df8db5cd4cdeeda380a131f950645"
        }
      ]
    }
  ]
}
