{
  "formatVersion": "1.1",
  "component": {
    "group": "com.astropay",
    "module": "connect-native-kyc",
    "version": "1.0.16-alpha.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "nativeKycReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:kyc": "nativeKyc",
        "kyc": "nativeKyc",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "connect-native-kyc-1.0.16-alpha.1.aar",
          "url": "connect-native-kyc-1.0.16-alpha.1.aar",
          "size": 358658,
          "sha512": "aa01af056d73dba6597d72fe1c39334f81bfbab85a1bd1d922177582957b9bdba04b0cd215c61aaabe632f879c2a25c40fb0de7983739f254977d205466f6171",
          "sha256": "2b00d837dd5e63afc576abf7561b07b07af96cba4700474405ff8628fa0ae626",
          "sha1": "ac8dc75968b02582031422149f705fb50207ae36",
          "md5": "186e3ca25ad8b2a971874be66bc9ea28"
        }
      ]
    },
    {
      "name": "nativeKycReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:kyc": "nativeKyc",
        "kyc": "nativeKyc",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.caf.sdk",
          "module": "caf-sdk-bom",
          "version": {
            "requires": "7.14.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.caf.sdk",
          "module": "caffaceliveness"
        },
        {
          "group": "io.caf.sdk",
          "module": "caffaceliveness-ui"
        },
        {
          "group": "io.caf.sdk",
          "module": "caffaceliveness-providers-iproov-lite"
        },
        {
          "group": "io.caf.sdk",
          "module": "caffaceliveness-providers-facetec"
        },
        {
          "group": "io.caf.sdk",
          "module": "document-detector-ui",
          "excludes": [
            {
              "group": "org.tensorflow",
              "module": "tensorflow-lite-support-api"
            },
            {
              "group": "org.tensorflow",
              "module": "tensorflow-lite"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.04.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "connect-native-kyc-1.0.16-alpha.1.aar",
          "url": "connect-native-kyc-1.0.16-alpha.1.aar",
          "size": 358658,
          "sha512": "aa01af056d73dba6597d72fe1c39334f81bfbab85a1bd1d922177582957b9bdba04b0cd215c61aaabe632f879c2a25c40fb0de7983739f254977d205466f6171",
          "sha256": "2b00d837dd5e63afc576abf7561b07b07af96cba4700474405ff8628fa0ae626",
          "sha1": "ac8dc75968b02582031422149f705fb50207ae36",
          "md5": "186e3ca25ad8b2a971874be66bc9ea28"
        }
      ]
    },
    {
      "name": "nativeKycReleaseSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.ProductFlavor:kyc": "nativeKyc",
        "kyc": "nativeKyc",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "connect-native-kyc-1.0.16-alpha.1-sources.jar",
          "url": "connect-native-kyc-1.0.16-alpha.1-sources.jar",
          "size": 186181,
          "sha512": "d8ba043cb908d187a6ee3103ff753ba760f5c2751e2a253c4e296e11513ca69849c5904408e32c8bc8223e850c6d4fd83886145ca553a041ac386131b868f6bf",
          "sha256": "e4f9a377b65e320cbae731fed4310a929e831087275036547339435761906c94",
          "sha1": "d259e69258a40db4f35822c5c3244b93ac087eec",
          "md5": "c0977eeaf76dd48fd4c4145ee7f0cebd"
        }
      ]
    }
  ]
}
